name: clima
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Hạ xuống một chút để tương thích tốt hơn với các thư viện Lab 9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # CHUYỂN CÁC THƯ VIỆN VÀO ĐÂY
  http: ^1.1.0
  geolocator: ^10.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # KHAI BÁO HÌNH ẢNH Ở ĐÂY (Lưu ý thụt lề 2 dấu cách)
  assets:
    - images/location_background.jpg
    - images/city_background.jpg
